const axios = require('axios');
const { downloadContentFromMessage } = require('@whiskeysockets/baileys');
const { cmd } = require('../command');
const FormData = require('form-data');

cmd({
    pattern: "nano",
    alias: ["banana", "nanobanana"],
    react: "🍌",
    desc: "Generate/transform image using Nano Banana AI",
    category: "image",
    use: ".nano <prompt> (reply to image)",
    filename: __filename,
},
async (conn, mek, m, { from, quoted, body, reply }) => {
    try {
        // Must reply to an image
        if (!quoted || !quoted.imageMessage) {
            return reply("🖼️ Please reply to an image with `.nano <your prompt>`");
        }

        // Extract prompt from command (text after .nano)
        const prompt = body.split(' ').slice(1).join(' ').trim();
        if (!prompt) {
            return reply("✏️ Please provide a prompt.\nExample: `.nano make this a cartoon`");
        }

        await reply("⏳ Nano Banana is working on your image, please wait...");

        // Download image from WhatsApp
        const stream = await downloadContentFromMessage(
            quoted.imageMessage,
            'image'
        );
        let buffer = Buffer.from([]);
        for await (const chunk of stream) {
            buffer = Buffer.concat([buffer, chunk]);
        }

        // Upload image to temporary hosting
        const form = new FormData();
        form.append('file', buffer, {
            filename: 'nano.jpg',
            contentType: 'image/jpeg'
        });

        const uploadRes = await axios.post(
            'https://tmpfiles.org/api/v1/upload',
            form,
            { headers: form.getHeaders() }
        );

        const imageUrl = uploadRes.data.data.url.replace(
            'tmpfiles.org/',
            'tmpfiles.org/dl/'
        );

        // Call Nano Banana API
        const apiUrl = `https://api-faa.my.id/faa/nano-banana?imageUrl=${encodeURIComponent(imageUrl)}&prompt=${encodeURIComponent(prompt)}`;

        const apiRes = await axios.get(apiUrl, { timeout: 60000 });
        const apiData = apiRes.data;

        // Validate API response
        if (!apiData || (!apiData.result && !apiData.url && !apiData.image)) {
            console.error("Nano Banana API response:", JSON.stringify(apiData));
            return reply("❌ Nano Banana failed. API returned no image. Please try again.");
        }

        // Extract result image URL (handle different possible response keys)
        const resultUrl = apiData.result || apiData.url || apiData.image;

        // Send generated image back to WhatsApp
        await conn.sendMessage(
            from,
            {
                image: { url: resultUrl },
                caption: `> 🍌 *Nano Banana Result*\n> 📝 Prompt: ${prompt}\n> ✨ Generated by 𝐑𝐔𝐇𝐈𝐈𝐈😻🎀💗`
            },
            { quoted: m }
        );

    } catch (err) {
        console.error("NANO BANANA ERROR:", err.message || err);
        reply("❌ Nano Banana failed. Please try again later.");
    }
});
