const { cmd } = require('../command');
const axios = require('axios');
const qs = require('querystring');

cmd({
  pattern: "ytcomment",
  alias: ["fakecomment", "fakeytcomment", "ytc", "youtubecomment"],
  desc: "Generate a fake YouTube comment image",
  category: "image-tools",
  use: ".ytcomment text=<comment> username=<name> avatar=<url>",
  filename: __filename
}, async (conn, mek, m, { args, from, reply }) => {
  try {
    // If no arguments provided — show example usage
    if (!args.length) {
      return reply(
`🎬 *YouTube Fake Comment Generator*

✨ *Example Usage:*
.ytcomment text=This video is amazing! username=JohnDoe avatar=https://files.catbox.moe/q3igju.jpg

🧩 *Parameters:*
• text - The comment text
• username - YouTube username  
• avatar - Profile picture URL

💡 *Tip:* Use + or _ for spaces in text
Example: text=This+is+awesome!

📌 *Simple Example:*
.ytcomment text=Nice+video username=MyName avatar=https://i.ibb.co/example.jpg`
      );
    }

    // Join all args to handle spaces properly
    const fullArgs = args.join(' ');
    const params = {};

    // Parse key=value pairs
    const regex = /(\w+)=([^=]+?)(?=\s+\w+=|$)/g;
    let match;
    while ((match = regex.exec(fullArgs)) !== null) {
      params[match[1].toLowerCase()] = match[2].trim();
    }

    // Fallback: parse simple key=value format
    if (Object.keys(params).length === 0) {
      for (const token of args) {
        const [k, ...rest] = token.split("=");
        if (!k) continue;
        params[k.toLowerCase()] = rest.join("=").trim();
      }
    }

    // Get parameters with defaults
    const text = params.text || params.comment || params.msg || "Nice video! 🔥";
    const username = params.username || params.user || params.name || "YouTube User";
    const avatar = params.avatar || params.avatarurl || params.photo || params.pp || "https://i.ibb.co/KhYC4FY/default.png";

    // Validate required parameters
    if (!params.text && !params.comment) {
      return reply("❌ Please provide comment text!\n\n*Example:* .ytcomment text=Nice video! username=John avatar=https://example.com/photo.jpg");
    }

    await reply("⏳ Generating fake YouTube comment, please wait...");

    // Build query string
    const query = qs.stringify({
      text: text,
      username: username,
      avatar: avatar
    });

    const apiUrl = `https://api.deline.web.id/maker/ytcomment?${query}`;

    // Make API request
    const res = await axios.get(apiUrl, {
      responseType: 'arraybuffer',
      headers: { 
        'accept': '*/*',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
      },
      timeout: 30000
    });

    // Check if response is JSON (error)
    const contentType = (res.headers['content-type'] || '').toLowerCase();
    if (contentType.includes('application/json')) {
      const textData = Buffer.from(res.data).toString('utf8');
      let json;
      try { 
        json = JSON.parse(textData); 
      } catch (e) { 
        json = { error: textData }; 
      }
      const errMsg = json.error || json.message || JSON.stringify(json);
      return reply(`❌ API Error: ${errMsg}`);
    }

    // Send the generated image
    const imageBuffer = Buffer.from(res.data);
    await conn.sendMessage(from, {
      image: imageBuffer,
      caption: `✅ *Fake YouTube Comment Generated!*\n\n👤 *Username:* ${username}\n💬 *Comment:* ${text}\n\n_Generated by DARKZONE-MD_`
    }, { quoted: mek });

  } catch (err) {
    console.error("YTComment Error:", err.message);
    if (err.code === 'ECONNABORTED') {
      return reply("❌ Request timed out. Please try again later.");
    }
    if (err.response && err.response.status) {
      return reply(`❌ API error: HTTP ${err.response.status}`);
    }
    return reply("❌ Failed to generate fake YouTube comment. Please try again later.");
  }
});
